name: build

on:
  pull_request:

jobs:
  cancel-previous-workflows:
    name: Cancel previous workflow runs
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew build

      - uses: actions/cache@v3
        name: Download base
        with:
          path: diffuse-source-file
          key: diffuse-${{ github.event.pull_request.base.sha }}

      - id: diffuse
        uses: usefulness/diffuse-action@v0.9.0
        with:
          old-file-path: diffuse-source-file
          new-file-path: diffuse/build/libs/diffuse-unspecified-r8.jar

      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Diffuse output

      - uses: peter-evans/create-or-update-comment@v3
        if: ${{ steps.diffuse.outputs.diff-raw != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            ### Jar size:
            Jar size change: ${{ steps.diffuse.outputs.size-diff-comment_style_1 }}

            ### Diffuse output:
            ${{ steps.diffuse.outputs.diff-gh-comment }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: diffuse-output
          path: ${{ steps.diffuse.outputs.diff-file }}
